---
title: "Assignment1"
author: "costanzadeacutis"
date: "2023-01-14"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}

rm(list=ls())

# Import libraries
library(tidyverse)
library(lspline)
library(cowplot)
library(boot)
library(estimatr)
library(huxtable)
library(stargazer)
library(modelsummary)
library(janitor)

knitr::opts_chunk$set(echo = TRUE)
```


# Dataset
Import data

```{r dataset}
cps <- read_csv("morg-2014-emp.csv", 
                     col_types = cols(.default = "?", 
                                      state = "c"))
#janitor::tabyl(data_all$state)
```

# Select occupation 
Keep only 2 occupation types: Artists and related workers and Food Preparation and Serving Related Occupations

```{r occupation}
cps <- cps %>% mutate(sample=ifelse(occ2012==2600,1,
                                              ifelse(cps$occ2012>=4000 & cps$occ2012<=4150,2,0)))

cps <- cps %>% filter(sample==1 | sample==2)
tabulate(cps$sample)
```

# Create variables

```{r variables}

# Earnings per hour and female
cps <- cps %>% mutate(earnhours=earnwke/uhours, 
                      lnw=log(earnhours),
                      female=as.numeric(sex==2)
)

# Age and Education
cps <- cps %>% mutate(agesq=age^2,
                      ed_lessBA=as.numeric(grade92<43),
                      ed_BA=as.numeric(grade92==43),
                      ed_MA=as.numeric(grade92==44),
                      ed_Profess = as.numeric(grade92==45),
                      ed_PhD = as.numeric(grade92==46)
)

# Race 
cps <- cps %>% mutate(white=as.numeric(race==1),
                      afram = as.numeric(race==2),
                      asian = as.numeric(race==4),
                      hisp = ifelse(!is.na(ethnic),1,0),
                      othernonw = as.numeric(white==0 & afram==0 & asian==0 & hisp==0),
                      nonUSborn = as.numeric(prcitshp=="Foreign Born, US Cit By Naturalization" | prcitshp=="Foreign Born, Not a US Citizen") 
)

# Potentially endogeneous demographics
cps <- cps %>% mutate(married = as.numeric(marital==1 | marital==2),
                      divorced = as.numeric(marital==3 | marital==5 | marital==6),
                      wirowed = as.numeric(marital==4),
                      nevermar = as.numeric(marital==7),
                      
                      child0 = as.numeric(chldpres==0),
                      child1 = as.numeric(chldpres==1),
                      child2 = as.numeric(chldpres==2),
                      child3 = as.numeric(chldpres==3),
                      child4pl = as.numeric(chldpres>=4))

# Work-related variables
cps <- cps %>% mutate(fedgov = as.numeric(class=="Government - Federal"),
                      stagov = as.numeric(class=="Government - State"),
                      locgov = as.numeric(class=="Government - Local"),
                      nonprof = as.numeric(class=="Private, Nonprofit"),
                      ind2dig = as.integer(as.numeric(as.factor(ind02))/100),
                      occ2dig = as.integer(occ2012/100),
                      union = as.numeric(unionmme=="Yes" | unioncov=="Yes"))

glimpse(cps)
```


# Models, predictors:
1. female, age
2. female, age, age^2
3. female, age, age^2, educ
4. female, age, age^2, educ, race

```{r models}
reg1 <- lm_robust(lnw ~ female + age, data=cps, se_type = "HC1")

reg2 <- lm_robust(lnw ~ female + age + agesq, data=cps, se_type = "HC1")

reg3 <- lm_robust(lnw ~ female + age + agesq + ed_BA + ed_MA + ed_Profess + ed_PhD, data=cps, se_type = "HC1")

reg4 <- lm_robust(lnw ~ female + age + agesq + ed_BA + ed_MA + ed_Profess + ed_PhD + afram + asian + hisp + othernonw + nonUSborn, data=cps, se_type = "HC1")

huxreg(reg1, reg2, reg3, reg4,statistics = c(N = "nobs", R2 = "r.squared"))
```


